name: fun
services:
  dozzle:
    container_name: fab-dozzle
    image: amir20/dozzle:v7.0.7
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/dozzle/data:/data
    ports:
      - 49152:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple

  postgres:
    container_name: fun-postgres
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      PG_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - fab_pg_data:/var/lib/postgresql/data
    networks:
      - fab_shared_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 7

  backend:
    container_name: fab-backend
    restart: always
    build:
      context: ./funb
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    networks:
      - fab_shared_network
    depends_on:
      postgres:
        condition: service_healthy
    command: sh /app/start.sh

  frontend:
    container_name: fab-frontend
    restart: always
    build:
      context: ./fun
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - fab_shared_network

volumes:
  fab_pg_data:

networks:
  fab_shared_network:
    driver: bridge
